name: Send a cat

on:
  pull_request_target:
    types: [opened]

jobs:
  send-a-cat:
    name: A cat for your effort!
    runs-on: ubuntu-latest
    steps:
      - uses: ruairidhwm/action-cats@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
